stages:
  - test

2fa-test-job:
  stage: test
  when: always
  script:
    - export VAULT_ADDR="http://127.0.0.1:8200"
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=testapp jwt=$CI_JOB_JWT)"
    - TELEGRAM_API_TOKEN=$(vault kv get -field=telegram_api_token secret/test/telegram_api_token)
      TEST_USER_ID=$(vault kv get -field=user_id secret/test/user_id)
      TEST_USER_NAME=$(vault kv get -field=user_name secret/test/user_name)
      TEST_USER_PASSWORD=$(vault kv get -field=user_password secret/test/user_password)
      go test -v ./internal/adapters/server/middleware
